import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../../../data/services/connectors/github_connector_service.dart';
import '../../../core/theme/elynos_theme.dart';

class CodeArtifactCard extends StatefulWidget {
  final String code;

  const CodeArtifactCard({super.key, required this.code});

  @override
  State<CodeArtifactCard> createState() => _CodeArtifactCardState();
}

class _CodeArtifactCardState extends State<CodeArtifactCard> {
  bool _isPushing = false;
  String? _statusMessage;

  Future<void> _handlePushToGitHub() async {
    setState(() {
      _isPushing = true;
      _statusMessage = null;
    });

    final github = GitHubConnectorService();
    final result = await github.pushProject(
      repoName: 'elynos-generated-app-${DateTime.now().millisecondsSinceEpoch}',
      description: 'Autonomous application generated by Elynos AI',
      files: {
        'index.html': widget.code,
      },
    );

    setState(() {
      _isPushing = false;
      _statusMessage = result.message;
    });

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(result.message),
          backgroundColor: result.success ? Colors.green : Colors.redAccent,
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 10),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: const Color(0xFF141922),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: ElyonsColors.accent.withOpacity(0.4), width: 1),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(6),
                decoration: BoxDecoration(
                  color: ElyonsColors.accent.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Icon(Icons.code_rounded, color: ElyonsColors.accent, size: 18),
              ),
              const SizedBox(width: 10),
              const Expanded(
                child: Text(
                  'Autonomous Build Artifact',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Colors.white),
                ),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: Colors.green.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: const Text(
                  'Ready',
                  style: TextStyle(fontSize: 11, color: Colors.greenAccent, fontWeight: FontWeight.bold),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          // Actions: Live Preview and Push to GitHub
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: () {
                    // Preview dialog
                    showDialog(
                      context: context,
                      builder: (ctx) => AlertDialog(
                        backgroundColor: const Color(0xFF161B22),
                        title: const Text('Live Sandbox Preview'),
                        content: SingleChildScrollView(
                          child: SelectableText(
                            widget.code,
                            style: const TextStyle(fontFamily: 'monospace', fontSize: 12),
                          ),
                        ),
                        actions: [
                          TextButton(
                            onPressed: () => Navigator.pop(ctx),
                            child: const Text('Close'),
                          ),
                        ],
                      ),
                    );
                  },
                  icon: const Icon(Icons.play_arrow_rounded, size: 16),
                  label: const Text('Preview'),
                  style: OutlinedButton.styleFrom(
                    foregroundColor: ElyonsColors.accent,
                    side: const BorderSide(color: ElyonsColors.border),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: _isPushing ? null : _handlePushToGitHub,
                  icon: _isPushing
                      ? const SizedBox(
                          width: 14,
                          height: 14,
                          child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black),
                        )
                      : const Icon(Icons.cloud_upload_outlined, size: 16),
                  label: Text(_isPushing ? 'Pushing...' : 'Push to GitHub'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: ElyonsColors.accent,
                    foregroundColor: Colors.black,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                ),
              ),
            ],
          ),
          if (_statusMessage != null) ...[
            const SizedBox(height: 8),
            Text(
              _statusMessage!,
              style: TextStyle(
                fontSize: 12,
                color: _statusMessage!.contains('Success') ? Colors.greenAccent : Colors.orangeAccent,
              ),
            ),
          ],
        ],
      ),
    );
  }
}
